name: Create release

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: false

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'

jobs:
  Fetch:
    if: ${{ github.event_name == 'workflow_dispatch' }} || github.event.pull_request.merged == true
    runs-on: self-hosted
    outputs:
      package: ${{ steps.version.outputs.package }}
      version: ${{ steps.version.outputs.version }}
      revision: ${{ steps.version.outputs.revision }}
    environment:
      name: release
    steps:
      - name: Fetch repository
        uses: actions/checkout@v4
        with:
          path: master

      - name: Fetch void-packages
        uses: actions/checkout@v4
        with:
          repository: void-linux/void-packages
          path: void-packages

      - name: Configure void-packages
        run: |
          cp -r master/void-packages ./ 2>/dev/null

      - id: version
        run: |
          echo "package=ungoogled-chromium" >> $GITHUB_OUTPUT
          echo "version=$( cat master/void-packages/srcpkgs/ungoogled-chromium/template | grep -m 1 'version=' | awk -F '=' '{ print $2 }' )" >> $GITHUB_OUTPUT
          echo "revision=$( cat master/void-packages/srcpkgs/ungoogled-chromium/template | grep -m 1 'revision=' | awk -F '=' '{ print $2 }' )" >> $GITHUB_OUTPUT

  Build:
    needs: [Fetch]
    strategy:
      max-parallel: 1
      matrix:
        arch: [x86_64-musl]
        exclude:
          - arch: x86_64-musl]
    runs-on: self-hosted
    timeout-minutes: 720
    steps:
      - name: Bootstrap ${{ matrix.arch }}
        run: |
          cd void-packages
          ./xbps-src -H /repository -A ${{ matrix.arch }} binary-bootstrap
      - name: Build ${{ matrix.arch }}
        run: |
          cd void-packages
          ./xbps-src -H /repository -A ${{ matrix.arch }} fetch ${{ needs.Fetch.outputs.package }}
          ./xbps-src -H /repository -A ${{ matrix.arch }} -C pkg ${{ needs.Fetch.outputs.package }}

  Build-aarch:
    needs: [Fetch, Build]
    strategy:
      max-parallel: 1
      matrix:
        arch: [aarch64, aarch64-musl]
        exclude:
          - arch: aarch64-musl
    runs-on: self-hosted
    timeout-minutes: 720
    steps:
      - name: Build ${{ matrix.arch }}
        run: |
          cd void-packages
          ./xbps-src -H /repository -a ${{ matrix.arch }} fetch ${{ needs.Fetch.outputs.package }}
          ./xbps-src -H /repository -a ${{ matrix.arch }} -C pkg ${{ needs.Fetch.outputs.package }}

  Sign:
    needs: [Fetch, Build, Build-aarch]
    strategy:
      max-parallel: 1
      matrix:
        arch: [x86_64, aarch64, aarch64-musl]
        exclude:
          - arch: aarch64-musl
    runs-on: self-hosted
    env:
      XBPS_TARGET_ARCH: ${{ matrix.arch }}
    steps:
      - name: Sign ${{ matrix.arch }} package
        run: |
          cd /repository/binpkgs
          rm -f ${{ matrix.arch }}-repodata
          xbps-rindex --add $PWD/${{ needs.Fetch.outputs.package }}-${{ needs.Fetch.outputs.version }}_${{ needs.Fetch.outputs.revision }}.${{ matrix.arch }}.xbps
          XBPS_PASSPHRASE=${{ secrets.SUPERBIA }} xbps-rindex --sign --signedby "xJayMorex" --privkey /repository/xJayMorex.pem $PWD
          XBPS_PASSPHRASE=${{ secrets.SUPERBIA }} xbps-rindex --sign-pkg --privkey /repository/xJayMorex.pem \
            $PWD/${{ needs.Fetch.outputs.package }}-${{ needs.Fetch.outputs.version }}_${{ needs.Fetch.outputs.revision }}.${{ matrix.arch }}.xbps
          sha256sum ${{ needs.Fetch.outputs.package }}-${{ needs.Fetch.outputs.version }}_${{ needs.Fetch.outputs.revision }}.${{ matrix.arch }}.xbps > \
            ${{ needs.Fetch.outputs.package }}-${{ needs.Fetch.outputs.version }}_${{ needs.Fetch.outputs.revision }}.${{ matrix.arch }}.xbps.sha256sum

  Release:
    needs: [Fetch, Sign]
    runs-on: self-hosted
    steps:
      - name: Checksum check
        run: |
          cd /repository/binpkgs
          cat ${{ needs.Fetch.outputs.package }}-${{ needs.Fetch.outputs.version }}_${{ needs.Fetch.outputs.revision }}.*.xbps.sha256sum | sha256sum -c

      - name: Publish
        uses: softprops/action-gh-release@v2
        with:
          body: |
            "Chromium release: <a href='https://chromium.googlesource.com/chromium/src/+/refs/tags/${{ needs.Fetch.outputs.version }}'>${{ needs.Fetch.outputs.version }}</a><br>
            Ungoogled Chromium release: <a href='https://github.com/ungoogled-software/ungoogled-chromium/releases/tag/${{ needs.Fetch.outputs.version }}-${{ needs.Fetch.outputs.revision }}'>${{ needs.Fetch.outputs.version }}-${{ needs.Fetch.outputs.revision }}</a>"
          files: |
            /repository/binpkgs/${{ needs.Fetch.outputs.package }}-${{ needs.Fetch.outputs.version }}_${{ needs.Fetch.outputs.revision }}.*.xbps
            /repository/binpkgs/${{ needs.Fetch.outputs.package }}-${{ needs.Fetch.outputs.version }}_${{ needs.Fetch.outputs.revision }}.*.xbps.sha256sum
            /repository/binpkgs/${{ needs.Fetch.outputs.package }}-${{ needs.Fetch.outputs.version }}_${{ needs.Fetch.outputs.revision }}.*.sig2
            /repository/binpkgs/*-repodata
          tag_name: "${{ needs.Fetch.outputs.version }}_${{ needs.Fetch.outputs.revision }}"

  Cleanup:
    needs: [Release]
    runs-on: self-hosted
    steps:
      - name: Cleanup old release files
        uses: dev-drprasad/delete-older-releases@v0.3.4
        with:
          keep_latest: 5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
